// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/otohacatalogmodel"
)

// OtohaCatalogModelCreate is the builder for creating a OtohaCatalogModel entity.
type OtohaCatalogModelCreate struct {
	config
	mutation *OtohaCatalogModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OtohaCatalogModelCreate) SetCreatedAt(v time.Time) *OtohaCatalogModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableCreatedAt(v *time.Time) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OtohaCatalogModelCreate) SetUpdatedAt(v time.Time) *OtohaCatalogModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableUpdatedAt(v *time.Time) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *OtohaCatalogModelCreate) SetGroupID(v int64) *OtohaCatalogModelCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *OtohaCatalogModelCreate) SetModelID(v string) *OtohaCatalogModelCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OtohaCatalogModelCreate) SetName(v string) *OtohaCatalogModelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableName(v *string) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *OtohaCatalogModelCreate) SetDescription(v string) *OtohaCatalogModelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableDescription(v *string) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *OtohaCatalogModelCreate) SetEnabled(v bool) *OtohaCatalogModelCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableEnabled(v *bool) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *OtohaCatalogModelCreate) SetSortOrder(v int) *OtohaCatalogModelCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableSortOrder(v *int) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetInputs sets the "inputs" field.
func (_c *OtohaCatalogModelCreate) SetInputs(v []string) *OtohaCatalogModelCreate {
	_c.mutation.SetInputs(v)
	return _c
}

// SetTools sets the "tools" field.
func (_c *OtohaCatalogModelCreate) SetTools(v bool) *OtohaCatalogModelCreate {
	_c.mutation.SetTools(v)
	return _c
}

// SetNillableTools sets the "tools" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableTools(v *bool) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetTools(*v)
	}
	return _c
}

// SetContextTokens sets the "context_tokens" field.
func (_c *OtohaCatalogModelCreate) SetContextTokens(v int) *OtohaCatalogModelCreate {
	_c.mutation.SetContextTokens(v)
	return _c
}

// SetNillableContextTokens sets the "context_tokens" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableContextTokens(v *int) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetContextTokens(*v)
	}
	return _c
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_c *OtohaCatalogModelCreate) SetMaxOutputTokens(v int) *OtohaCatalogModelCreate {
	_c.mutation.SetMaxOutputTokens(v)
	return _c
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableMaxOutputTokens(v *int) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetMaxOutputTokens(*v)
	}
	return _c
}

// SetReasoningLevels sets the "reasoning_levels" field.
func (_c *OtohaCatalogModelCreate) SetReasoningLevels(v []string) *OtohaCatalogModelCreate {
	_c.mutation.SetReasoningLevels(v)
	return _c
}

// SetDefaultReasoning sets the "default_reasoning" field.
func (_c *OtohaCatalogModelCreate) SetDefaultReasoning(v string) *OtohaCatalogModelCreate {
	_c.mutation.SetDefaultReasoning(v)
	return _c
}

// SetNillableDefaultReasoning sets the "default_reasoning" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableDefaultReasoning(v *string) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetDefaultReasoning(*v)
	}
	return _c
}

// SetSpeed sets the "speed" field.
func (_c *OtohaCatalogModelCreate) SetSpeed(v string) *OtohaCatalogModelCreate {
	_c.mutation.SetSpeed(v)
	return _c
}

// SetNillableSpeed sets the "speed" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableSpeed(v *string) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetSpeed(*v)
	}
	return _c
}

// SetStrengths sets the "strengths" field.
func (_c *OtohaCatalogModelCreate) SetStrengths(v map[string]string) *OtohaCatalogModelCreate {
	_c.mutation.SetStrengths(v)
	return _c
}

// SetComplexity sets the "complexity" field.
func (_c *OtohaCatalogModelCreate) SetComplexity(v string) *OtohaCatalogModelCreate {
	_c.mutation.SetComplexity(v)
	return _c
}

// SetNillableComplexity sets the "complexity" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableComplexity(v *string) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetComplexity(*v)
	}
	return _c
}

// SetRoles sets the "roles" field.
func (_c *OtohaCatalogModelCreate) SetRoles(v []string) *OtohaCatalogModelCreate {
	_c.mutation.SetRoles(v)
	return _c
}

// SetUses sets the "uses" field.
func (_c *OtohaCatalogModelCreate) SetUses(v []string) *OtohaCatalogModelCreate {
	_c.mutation.SetUses(v)
	return _c
}

// SetProfileSource sets the "profile_source" field.
func (_c *OtohaCatalogModelCreate) SetProfileSource(v string) *OtohaCatalogModelCreate {
	_c.mutation.SetProfileSource(v)
	return _c
}

// SetNillableProfileSource sets the "profile_source" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableProfileSource(v *string) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetProfileSource(*v)
	}
	return _c
}

// SetCostTier sets the "cost_tier" field.
func (_c *OtohaCatalogModelCreate) SetCostTier(v string) *OtohaCatalogModelCreate {
	_c.mutation.SetCostTier(v)
	return _c
}

// SetNillableCostTier sets the "cost_tier" field if the given value is not nil.
func (_c *OtohaCatalogModelCreate) SetNillableCostTier(v *string) *OtohaCatalogModelCreate {
	if v != nil {
		_c.SetCostTier(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *OtohaCatalogModelCreate) SetGroup(v *Group) *OtohaCatalogModelCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the OtohaCatalogModelMutation object of the builder.
func (_c *OtohaCatalogModelCreate) Mutation() *OtohaCatalogModelMutation {
	return _c.mutation
}

// Save creates the OtohaCatalogModel in the database.
func (_c *OtohaCatalogModelCreate) Save(ctx context.Context) (*OtohaCatalogModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OtohaCatalogModelCreate) SaveX(ctx context.Context) *OtohaCatalogModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OtohaCatalogModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OtohaCatalogModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OtohaCatalogModelCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := otohacatalogmodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := otohacatalogmodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := otohacatalogmodel.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := otohacatalogmodel.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := otohacatalogmodel.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := otohacatalogmodel.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Tools(); !ok {
		v := otohacatalogmodel.DefaultTools
		_c.mutation.SetTools(v)
	}
	if _, ok := _c.mutation.ContextTokens(); !ok {
		v := otohacatalogmodel.DefaultContextTokens
		_c.mutation.SetContextTokens(v)
	}
	if _, ok := _c.mutation.MaxOutputTokens(); !ok {
		v := otohacatalogmodel.DefaultMaxOutputTokens
		_c.mutation.SetMaxOutputTokens(v)
	}
	if _, ok := _c.mutation.DefaultReasoning(); !ok {
		v := otohacatalogmodel.DefaultDefaultReasoning
		_c.mutation.SetDefaultReasoning(v)
	}
	if _, ok := _c.mutation.Speed(); !ok {
		v := otohacatalogmodel.DefaultSpeed
		_c.mutation.SetSpeed(v)
	}
	if _, ok := _c.mutation.Complexity(); !ok {
		v := otohacatalogmodel.DefaultComplexity
		_c.mutation.SetComplexity(v)
	}
	if _, ok := _c.mutation.ProfileSource(); !ok {
		v := otohacatalogmodel.DefaultProfileSource
		_c.mutation.SetProfileSource(v)
	}
	if _, ok := _c.mutation.CostTier(); !ok {
		v := otohacatalogmodel.DefaultCostTier
		_c.mutation.SetCostTier(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OtohaCatalogModelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OtohaCatalogModel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OtohaCatalogModel.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "OtohaCatalogModel.group_id"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "OtohaCatalogModel.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := otohacatalogmodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OtohaCatalogModel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := otohacatalogmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "OtohaCatalogModel.description"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "OtohaCatalogModel.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "OtohaCatalogModel.sort_order"`)}
	}
	if _, ok := _c.mutation.Tools(); !ok {
		return &ValidationError{Name: "tools", err: errors.New(`ent: missing required field "OtohaCatalogModel.tools"`)}
	}
	if _, ok := _c.mutation.ContextTokens(); !ok {
		return &ValidationError{Name: "context_tokens", err: errors.New(`ent: missing required field "OtohaCatalogModel.context_tokens"`)}
	}
	if _, ok := _c.mutation.MaxOutputTokens(); !ok {
		return &ValidationError{Name: "max_output_tokens", err: errors.New(`ent: missing required field "OtohaCatalogModel.max_output_tokens"`)}
	}
	if _, ok := _c.mutation.DefaultReasoning(); !ok {
		return &ValidationError{Name: "default_reasoning", err: errors.New(`ent: missing required field "OtohaCatalogModel.default_reasoning"`)}
	}
	if v, ok := _c.mutation.DefaultReasoning(); ok {
		if err := otohacatalogmodel.DefaultReasoningValidator(v); err != nil {
			return &ValidationError{Name: "default_reasoning", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.default_reasoning": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Speed(); !ok {
		return &ValidationError{Name: "speed", err: errors.New(`ent: missing required field "OtohaCatalogModel.speed"`)}
	}
	if v, ok := _c.mutation.Speed(); ok {
		if err := otohacatalogmodel.SpeedValidator(v); err != nil {
			return &ValidationError{Name: "speed", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.speed": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Complexity(); !ok {
		return &ValidationError{Name: "complexity", err: errors.New(`ent: missing required field "OtohaCatalogModel.complexity"`)}
	}
	if v, ok := _c.mutation.Complexity(); ok {
		if err := otohacatalogmodel.ComplexityValidator(v); err != nil {
			return &ValidationError{Name: "complexity", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.complexity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProfileSource(); !ok {
		return &ValidationError{Name: "profile_source", err: errors.New(`ent: missing required field "OtohaCatalogModel.profile_source"`)}
	}
	if v, ok := _c.mutation.ProfileSource(); ok {
		if err := otohacatalogmodel.ProfileSourceValidator(v); err != nil {
			return &ValidationError{Name: "profile_source", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.profile_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CostTier(); !ok {
		return &ValidationError{Name: "cost_tier", err: errors.New(`ent: missing required field "OtohaCatalogModel.cost_tier"`)}
	}
	if v, ok := _c.mutation.CostTier(); ok {
		if err := otohacatalogmodel.CostTierValidator(v); err != nil {
			return &ValidationError{Name: "cost_tier", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.cost_tier": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "OtohaCatalogModel.group"`)}
	}
	return nil
}

func (_c *OtohaCatalogModelCreate) sqlSave(ctx context.Context) (*OtohaCatalogModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OtohaCatalogModelCreate) createSpec() (*OtohaCatalogModel, *sqlgraph.CreateSpec) {
	var (
		_node = &OtohaCatalogModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(otohacatalogmodel.Table, sqlgraph.NewFieldSpec(otohacatalogmodel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(otohacatalogmodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(otohacatalogmodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(otohacatalogmodel.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(otohacatalogmodel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(otohacatalogmodel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(otohacatalogmodel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(otohacatalogmodel.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Inputs(); ok {
		_spec.SetField(otohacatalogmodel.FieldInputs, field.TypeJSON, value)
		_node.Inputs = value
	}
	if value, ok := _c.mutation.Tools(); ok {
		_spec.SetField(otohacatalogmodel.FieldTools, field.TypeBool, value)
		_node.Tools = value
	}
	if value, ok := _c.mutation.ContextTokens(); ok {
		_spec.SetField(otohacatalogmodel.FieldContextTokens, field.TypeInt, value)
		_node.ContextTokens = value
	}
	if value, ok := _c.mutation.MaxOutputTokens(); ok {
		_spec.SetField(otohacatalogmodel.FieldMaxOutputTokens, field.TypeInt, value)
		_node.MaxOutputTokens = value
	}
	if value, ok := _c.mutation.ReasoningLevels(); ok {
		_spec.SetField(otohacatalogmodel.FieldReasoningLevels, field.TypeJSON, value)
		_node.ReasoningLevels = value
	}
	if value, ok := _c.mutation.DefaultReasoning(); ok {
		_spec.SetField(otohacatalogmodel.FieldDefaultReasoning, field.TypeString, value)
		_node.DefaultReasoning = value
	}
	if value, ok := _c.mutation.Speed(); ok {
		_spec.SetField(otohacatalogmodel.FieldSpeed, field.TypeString, value)
		_node.Speed = value
	}
	if value, ok := _c.mutation.Strengths(); ok {
		_spec.SetField(otohacatalogmodel.FieldStrengths, field.TypeJSON, value)
		_node.Strengths = value
	}
	if value, ok := _c.mutation.Complexity(); ok {
		_spec.SetField(otohacatalogmodel.FieldComplexity, field.TypeString, value)
		_node.Complexity = value
	}
	if value, ok := _c.mutation.Roles(); ok {
		_spec.SetField(otohacatalogmodel.FieldRoles, field.TypeJSON, value)
		_node.Roles = value
	}
	if value, ok := _c.mutation.Uses(); ok {
		_spec.SetField(otohacatalogmodel.FieldUses, field.TypeJSON, value)
		_node.Uses = value
	}
	if value, ok := _c.mutation.ProfileSource(); ok {
		_spec.SetField(otohacatalogmodel.FieldProfileSource, field.TypeString, value)
		_node.ProfileSource = value
	}
	if value, ok := _c.mutation.CostTier(); ok {
		_spec.SetField(otohacatalogmodel.FieldCostTier, field.TypeString, value)
		_node.CostTier = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   otohacatalogmodel.GroupTable,
			Columns: []string{otohacatalogmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OtohaCatalogModel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OtohaCatalogModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OtohaCatalogModelCreate) OnConflict(opts ...sql.ConflictOption) *OtohaCatalogModelUpsertOne {
	_c.conflict = opts
	return &OtohaCatalogModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OtohaCatalogModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OtohaCatalogModelCreate) OnConflictColumns(columns ...string) *OtohaCatalogModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OtohaCatalogModelUpsertOne{
		create: _c,
	}
}

type (
	// OtohaCatalogModelUpsertOne is the builder for "upsert"-ing
	//  one OtohaCatalogModel node.
	OtohaCatalogModelUpsertOne struct {
		create *OtohaCatalogModelCreate
	}

	// OtohaCatalogModelUpsert is the "OnConflict" setter.
	OtohaCatalogModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OtohaCatalogModelUpsert) SetUpdatedAt(v time.Time) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateUpdatedAt() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *OtohaCatalogModelUpsert) SetGroupID(v int64) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateGroupID() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldGroupID)
	return u
}

// SetModelID sets the "model_id" field.
func (u *OtohaCatalogModelUpsert) SetModelID(v string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateModelID() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldModelID)
	return u
}

// SetName sets the "name" field.
func (u *OtohaCatalogModelUpsert) SetName(v string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateName() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *OtohaCatalogModelUpsert) SetDescription(v string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateDescription() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldDescription)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *OtohaCatalogModelUpsert) SetEnabled(v bool) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateEnabled() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *OtohaCatalogModelUpsert) SetSortOrder(v int) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateSortOrder() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *OtohaCatalogModelUpsert) AddSortOrder(v int) *OtohaCatalogModelUpsert {
	u.Add(otohacatalogmodel.FieldSortOrder, v)
	return u
}

// SetInputs sets the "inputs" field.
func (u *OtohaCatalogModelUpsert) SetInputs(v []string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldInputs, v)
	return u
}

// UpdateInputs sets the "inputs" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateInputs() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldInputs)
	return u
}

// ClearInputs clears the value of the "inputs" field.
func (u *OtohaCatalogModelUpsert) ClearInputs() *OtohaCatalogModelUpsert {
	u.SetNull(otohacatalogmodel.FieldInputs)
	return u
}

// SetTools sets the "tools" field.
func (u *OtohaCatalogModelUpsert) SetTools(v bool) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldTools, v)
	return u
}

// UpdateTools sets the "tools" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateTools() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldTools)
	return u
}

// SetContextTokens sets the "context_tokens" field.
func (u *OtohaCatalogModelUpsert) SetContextTokens(v int) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldContextTokens, v)
	return u
}

// UpdateContextTokens sets the "context_tokens" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateContextTokens() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldContextTokens)
	return u
}

// AddContextTokens adds v to the "context_tokens" field.
func (u *OtohaCatalogModelUpsert) AddContextTokens(v int) *OtohaCatalogModelUpsert {
	u.Add(otohacatalogmodel.FieldContextTokens, v)
	return u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *OtohaCatalogModelUpsert) SetMaxOutputTokens(v int) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldMaxOutputTokens, v)
	return u
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateMaxOutputTokens() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldMaxOutputTokens)
	return u
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *OtohaCatalogModelUpsert) AddMaxOutputTokens(v int) *OtohaCatalogModelUpsert {
	u.Add(otohacatalogmodel.FieldMaxOutputTokens, v)
	return u
}

// SetReasoningLevels sets the "reasoning_levels" field.
func (u *OtohaCatalogModelUpsert) SetReasoningLevels(v []string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldReasoningLevels, v)
	return u
}

// UpdateReasoningLevels sets the "reasoning_levels" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateReasoningLevels() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldReasoningLevels)
	return u
}

// ClearReasoningLevels clears the value of the "reasoning_levels" field.
func (u *OtohaCatalogModelUpsert) ClearReasoningLevels() *OtohaCatalogModelUpsert {
	u.SetNull(otohacatalogmodel.FieldReasoningLevels)
	return u
}

// SetDefaultReasoning sets the "default_reasoning" field.
func (u *OtohaCatalogModelUpsert) SetDefaultReasoning(v string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldDefaultReasoning, v)
	return u
}

// UpdateDefaultReasoning sets the "default_reasoning" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateDefaultReasoning() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldDefaultReasoning)
	return u
}

// SetSpeed sets the "speed" field.
func (u *OtohaCatalogModelUpsert) SetSpeed(v string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldSpeed, v)
	return u
}

// UpdateSpeed sets the "speed" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateSpeed() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldSpeed)
	return u
}

// SetStrengths sets the "strengths" field.
func (u *OtohaCatalogModelUpsert) SetStrengths(v map[string]string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldStrengths, v)
	return u
}

// UpdateStrengths sets the "strengths" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateStrengths() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldStrengths)
	return u
}

// ClearStrengths clears the value of the "strengths" field.
func (u *OtohaCatalogModelUpsert) ClearStrengths() *OtohaCatalogModelUpsert {
	u.SetNull(otohacatalogmodel.FieldStrengths)
	return u
}

// SetComplexity sets the "complexity" field.
func (u *OtohaCatalogModelUpsert) SetComplexity(v string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldComplexity, v)
	return u
}

// UpdateComplexity sets the "complexity" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateComplexity() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldComplexity)
	return u
}

// SetRoles sets the "roles" field.
func (u *OtohaCatalogModelUpsert) SetRoles(v []string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldRoles, v)
	return u
}

// UpdateRoles sets the "roles" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateRoles() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldRoles)
	return u
}

// ClearRoles clears the value of the "roles" field.
func (u *OtohaCatalogModelUpsert) ClearRoles() *OtohaCatalogModelUpsert {
	u.SetNull(otohacatalogmodel.FieldRoles)
	return u
}

// SetUses sets the "uses" field.
func (u *OtohaCatalogModelUpsert) SetUses(v []string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldUses, v)
	return u
}

// UpdateUses sets the "uses" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateUses() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldUses)
	return u
}

// ClearUses clears the value of the "uses" field.
func (u *OtohaCatalogModelUpsert) ClearUses() *OtohaCatalogModelUpsert {
	u.SetNull(otohacatalogmodel.FieldUses)
	return u
}

// SetProfileSource sets the "profile_source" field.
func (u *OtohaCatalogModelUpsert) SetProfileSource(v string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldProfileSource, v)
	return u
}

// UpdateProfileSource sets the "profile_source" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateProfileSource() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldProfileSource)
	return u
}

// SetCostTier sets the "cost_tier" field.
func (u *OtohaCatalogModelUpsert) SetCostTier(v string) *OtohaCatalogModelUpsert {
	u.Set(otohacatalogmodel.FieldCostTier, v)
	return u
}

// UpdateCostTier sets the "cost_tier" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsert) UpdateCostTier() *OtohaCatalogModelUpsert {
	u.SetExcluded(otohacatalogmodel.FieldCostTier)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OtohaCatalogModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OtohaCatalogModelUpsertOne) UpdateNewValues() *OtohaCatalogModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(otohacatalogmodel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OtohaCatalogModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OtohaCatalogModelUpsertOne) Ignore() *OtohaCatalogModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OtohaCatalogModelUpsertOne) DoNothing() *OtohaCatalogModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OtohaCatalogModelCreate.OnConflict
// documentation for more info.
func (u *OtohaCatalogModelUpsertOne) Update(set func(*OtohaCatalogModelUpsert)) *OtohaCatalogModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OtohaCatalogModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OtohaCatalogModelUpsertOne) SetUpdatedAt(v time.Time) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateUpdatedAt() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OtohaCatalogModelUpsertOne) SetGroupID(v int64) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateGroupID() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateGroupID()
	})
}

// SetModelID sets the "model_id" field.
func (u *OtohaCatalogModelUpsertOne) SetModelID(v string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateModelID() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateModelID()
	})
}

// SetName sets the "name" field.
func (u *OtohaCatalogModelUpsertOne) SetName(v string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateName() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *OtohaCatalogModelUpsertOne) SetDescription(v string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateDescription() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *OtohaCatalogModelUpsertOne) SetEnabled(v bool) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateEnabled() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *OtohaCatalogModelUpsertOne) SetSortOrder(v int) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *OtohaCatalogModelUpsertOne) AddSortOrder(v int) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateSortOrder() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateSortOrder()
	})
}

// SetInputs sets the "inputs" field.
func (u *OtohaCatalogModelUpsertOne) SetInputs(v []string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetInputs(v)
	})
}

// UpdateInputs sets the "inputs" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateInputs() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateInputs()
	})
}

// ClearInputs clears the value of the "inputs" field.
func (u *OtohaCatalogModelUpsertOne) ClearInputs() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearInputs()
	})
}

// SetTools sets the "tools" field.
func (u *OtohaCatalogModelUpsertOne) SetTools(v bool) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetTools(v)
	})
}

// UpdateTools sets the "tools" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateTools() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateTools()
	})
}

// SetContextTokens sets the "context_tokens" field.
func (u *OtohaCatalogModelUpsertOne) SetContextTokens(v int) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetContextTokens(v)
	})
}

// AddContextTokens adds v to the "context_tokens" field.
func (u *OtohaCatalogModelUpsertOne) AddContextTokens(v int) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.AddContextTokens(v)
	})
}

// UpdateContextTokens sets the "context_tokens" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateContextTokens() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateContextTokens()
	})
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *OtohaCatalogModelUpsertOne) SetMaxOutputTokens(v int) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetMaxOutputTokens(v)
	})
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *OtohaCatalogModelUpsertOne) AddMaxOutputTokens(v int) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.AddMaxOutputTokens(v)
	})
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateMaxOutputTokens() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateMaxOutputTokens()
	})
}

// SetReasoningLevels sets the "reasoning_levels" field.
func (u *OtohaCatalogModelUpsertOne) SetReasoningLevels(v []string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetReasoningLevels(v)
	})
}

// UpdateReasoningLevels sets the "reasoning_levels" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateReasoningLevels() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateReasoningLevels()
	})
}

// ClearReasoningLevels clears the value of the "reasoning_levels" field.
func (u *OtohaCatalogModelUpsertOne) ClearReasoningLevels() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearReasoningLevels()
	})
}

// SetDefaultReasoning sets the "default_reasoning" field.
func (u *OtohaCatalogModelUpsertOne) SetDefaultReasoning(v string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetDefaultReasoning(v)
	})
}

// UpdateDefaultReasoning sets the "default_reasoning" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateDefaultReasoning() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateDefaultReasoning()
	})
}

// SetSpeed sets the "speed" field.
func (u *OtohaCatalogModelUpsertOne) SetSpeed(v string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetSpeed(v)
	})
}

// UpdateSpeed sets the "speed" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateSpeed() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateSpeed()
	})
}

// SetStrengths sets the "strengths" field.
func (u *OtohaCatalogModelUpsertOne) SetStrengths(v map[string]string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetStrengths(v)
	})
}

// UpdateStrengths sets the "strengths" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateStrengths() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateStrengths()
	})
}

// ClearStrengths clears the value of the "strengths" field.
func (u *OtohaCatalogModelUpsertOne) ClearStrengths() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearStrengths()
	})
}

// SetComplexity sets the "complexity" field.
func (u *OtohaCatalogModelUpsertOne) SetComplexity(v string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetComplexity(v)
	})
}

// UpdateComplexity sets the "complexity" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateComplexity() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateComplexity()
	})
}

// SetRoles sets the "roles" field.
func (u *OtohaCatalogModelUpsertOne) SetRoles(v []string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetRoles(v)
	})
}

// UpdateRoles sets the "roles" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateRoles() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateRoles()
	})
}

// ClearRoles clears the value of the "roles" field.
func (u *OtohaCatalogModelUpsertOne) ClearRoles() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearRoles()
	})
}

// SetUses sets the "uses" field.
func (u *OtohaCatalogModelUpsertOne) SetUses(v []string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetUses(v)
	})
}

// UpdateUses sets the "uses" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateUses() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateUses()
	})
}

// ClearUses clears the value of the "uses" field.
func (u *OtohaCatalogModelUpsertOne) ClearUses() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearUses()
	})
}

// SetProfileSource sets the "profile_source" field.
func (u *OtohaCatalogModelUpsertOne) SetProfileSource(v string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetProfileSource(v)
	})
}

// UpdateProfileSource sets the "profile_source" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateProfileSource() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateProfileSource()
	})
}

// SetCostTier sets the "cost_tier" field.
func (u *OtohaCatalogModelUpsertOne) SetCostTier(v string) *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetCostTier(v)
	})
}

// UpdateCostTier sets the "cost_tier" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertOne) UpdateCostTier() *OtohaCatalogModelUpsertOne {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateCostTier()
	})
}

// Exec executes the query.
func (u *OtohaCatalogModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OtohaCatalogModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OtohaCatalogModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OtohaCatalogModelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OtohaCatalogModelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OtohaCatalogModelCreateBulk is the builder for creating many OtohaCatalogModel entities in bulk.
type OtohaCatalogModelCreateBulk struct {
	config
	err      error
	builders []*OtohaCatalogModelCreate
	conflict []sql.ConflictOption
}

// Save creates the OtohaCatalogModel entities in the database.
func (_c *OtohaCatalogModelCreateBulk) Save(ctx context.Context) ([]*OtohaCatalogModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OtohaCatalogModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OtohaCatalogModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OtohaCatalogModelCreateBulk) SaveX(ctx context.Context) []*OtohaCatalogModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OtohaCatalogModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OtohaCatalogModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OtohaCatalogModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OtohaCatalogModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OtohaCatalogModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *OtohaCatalogModelUpsertBulk {
	_c.conflict = opts
	return &OtohaCatalogModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OtohaCatalogModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OtohaCatalogModelCreateBulk) OnConflictColumns(columns ...string) *OtohaCatalogModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OtohaCatalogModelUpsertBulk{
		create: _c,
	}
}

// OtohaCatalogModelUpsertBulk is the builder for "upsert"-ing
// a bulk of OtohaCatalogModel nodes.
type OtohaCatalogModelUpsertBulk struct {
	create *OtohaCatalogModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OtohaCatalogModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OtohaCatalogModelUpsertBulk) UpdateNewValues() *OtohaCatalogModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(otohacatalogmodel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OtohaCatalogModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OtohaCatalogModelUpsertBulk) Ignore() *OtohaCatalogModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OtohaCatalogModelUpsertBulk) DoNothing() *OtohaCatalogModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OtohaCatalogModelCreateBulk.OnConflict
// documentation for more info.
func (u *OtohaCatalogModelUpsertBulk) Update(set func(*OtohaCatalogModelUpsert)) *OtohaCatalogModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OtohaCatalogModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OtohaCatalogModelUpsertBulk) SetUpdatedAt(v time.Time) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateUpdatedAt() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OtohaCatalogModelUpsertBulk) SetGroupID(v int64) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateGroupID() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateGroupID()
	})
}

// SetModelID sets the "model_id" field.
func (u *OtohaCatalogModelUpsertBulk) SetModelID(v string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateModelID() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateModelID()
	})
}

// SetName sets the "name" field.
func (u *OtohaCatalogModelUpsertBulk) SetName(v string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateName() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *OtohaCatalogModelUpsertBulk) SetDescription(v string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateDescription() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *OtohaCatalogModelUpsertBulk) SetEnabled(v bool) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateEnabled() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *OtohaCatalogModelUpsertBulk) SetSortOrder(v int) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *OtohaCatalogModelUpsertBulk) AddSortOrder(v int) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateSortOrder() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateSortOrder()
	})
}

// SetInputs sets the "inputs" field.
func (u *OtohaCatalogModelUpsertBulk) SetInputs(v []string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetInputs(v)
	})
}

// UpdateInputs sets the "inputs" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateInputs() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateInputs()
	})
}

// ClearInputs clears the value of the "inputs" field.
func (u *OtohaCatalogModelUpsertBulk) ClearInputs() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearInputs()
	})
}

// SetTools sets the "tools" field.
func (u *OtohaCatalogModelUpsertBulk) SetTools(v bool) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetTools(v)
	})
}

// UpdateTools sets the "tools" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateTools() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateTools()
	})
}

// SetContextTokens sets the "context_tokens" field.
func (u *OtohaCatalogModelUpsertBulk) SetContextTokens(v int) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetContextTokens(v)
	})
}

// AddContextTokens adds v to the "context_tokens" field.
func (u *OtohaCatalogModelUpsertBulk) AddContextTokens(v int) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.AddContextTokens(v)
	})
}

// UpdateContextTokens sets the "context_tokens" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateContextTokens() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateContextTokens()
	})
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *OtohaCatalogModelUpsertBulk) SetMaxOutputTokens(v int) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetMaxOutputTokens(v)
	})
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *OtohaCatalogModelUpsertBulk) AddMaxOutputTokens(v int) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.AddMaxOutputTokens(v)
	})
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateMaxOutputTokens() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateMaxOutputTokens()
	})
}

// SetReasoningLevels sets the "reasoning_levels" field.
func (u *OtohaCatalogModelUpsertBulk) SetReasoningLevels(v []string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetReasoningLevels(v)
	})
}

// UpdateReasoningLevels sets the "reasoning_levels" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateReasoningLevels() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateReasoningLevels()
	})
}

// ClearReasoningLevels clears the value of the "reasoning_levels" field.
func (u *OtohaCatalogModelUpsertBulk) ClearReasoningLevels() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearReasoningLevels()
	})
}

// SetDefaultReasoning sets the "default_reasoning" field.
func (u *OtohaCatalogModelUpsertBulk) SetDefaultReasoning(v string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetDefaultReasoning(v)
	})
}

// UpdateDefaultReasoning sets the "default_reasoning" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateDefaultReasoning() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateDefaultReasoning()
	})
}

// SetSpeed sets the "speed" field.
func (u *OtohaCatalogModelUpsertBulk) SetSpeed(v string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetSpeed(v)
	})
}

// UpdateSpeed sets the "speed" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateSpeed() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateSpeed()
	})
}

// SetStrengths sets the "strengths" field.
func (u *OtohaCatalogModelUpsertBulk) SetStrengths(v map[string]string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetStrengths(v)
	})
}

// UpdateStrengths sets the "strengths" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateStrengths() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateStrengths()
	})
}

// ClearStrengths clears the value of the "strengths" field.
func (u *OtohaCatalogModelUpsertBulk) ClearStrengths() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearStrengths()
	})
}

// SetComplexity sets the "complexity" field.
func (u *OtohaCatalogModelUpsertBulk) SetComplexity(v string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetComplexity(v)
	})
}

// UpdateComplexity sets the "complexity" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateComplexity() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateComplexity()
	})
}

// SetRoles sets the "roles" field.
func (u *OtohaCatalogModelUpsertBulk) SetRoles(v []string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetRoles(v)
	})
}

// UpdateRoles sets the "roles" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateRoles() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateRoles()
	})
}

// ClearRoles clears the value of the "roles" field.
func (u *OtohaCatalogModelUpsertBulk) ClearRoles() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearRoles()
	})
}

// SetUses sets the "uses" field.
func (u *OtohaCatalogModelUpsertBulk) SetUses(v []string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetUses(v)
	})
}

// UpdateUses sets the "uses" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateUses() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateUses()
	})
}

// ClearUses clears the value of the "uses" field.
func (u *OtohaCatalogModelUpsertBulk) ClearUses() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.ClearUses()
	})
}

// SetProfileSource sets the "profile_source" field.
func (u *OtohaCatalogModelUpsertBulk) SetProfileSource(v string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetProfileSource(v)
	})
}

// UpdateProfileSource sets the "profile_source" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateProfileSource() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateProfileSource()
	})
}

// SetCostTier sets the "cost_tier" field.
func (u *OtohaCatalogModelUpsertBulk) SetCostTier(v string) *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.SetCostTier(v)
	})
}

// UpdateCostTier sets the "cost_tier" field to the value that was provided on create.
func (u *OtohaCatalogModelUpsertBulk) UpdateCostTier() *OtohaCatalogModelUpsertBulk {
	return u.Update(func(s *OtohaCatalogModelUpsert) {
		s.UpdateCostTier()
	})
}

// Exec executes the query.
func (u *OtohaCatalogModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OtohaCatalogModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OtohaCatalogModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OtohaCatalogModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
