// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/otohacatalogmodel"
)

// OtohaCatalogModel is the model entity for the OtohaCatalogModel schema.
type OtohaCatalogModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Model ID the app sends.
	ModelID string `json:"model_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Inputs holds the value of the "inputs" field.
	Inputs []string `json:"inputs,omitempty"`
	// Tools holds the value of the "tools" field.
	Tools bool `json:"tools,omitempty"`
	// ContextTokens holds the value of the "context_tokens" field.
	ContextTokens int `json:"context_tokens,omitempty"`
	// MaxOutputTokens holds the value of the "max_output_tokens" field.
	MaxOutputTokens int `json:"max_output_tokens,omitempty"`
	// ReasoningLevels holds the value of the "reasoning_levels" field.
	ReasoningLevels []string `json:"reasoning_levels,omitempty"`
	// DefaultReasoning holds the value of the "default_reasoning" field.
	DefaultReasoning string `json:"default_reasoning,omitempty"`
	// Speed holds the value of the "speed" field.
	Speed string `json:"speed,omitempty"`
	// Strengths holds the value of the "strengths" field.
	Strengths map[string]string `json:"strengths,omitempty"`
	// Complexity holds the value of the "complexity" field.
	Complexity string `json:"complexity,omitempty"`
	// Roles holds the value of the "roles" field.
	Roles []string `json:"roles,omitempty"`
	// Uses holds the value of the "uses" field.
	Uses []string `json:"uses,omitempty"`
	// ProfileSource holds the value of the "profile_source" field.
	ProfileSource string `json:"profile_source,omitempty"`
	// Empty derives the tier from the sale price.
	CostTier string `json:"cost_tier,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OtohaCatalogModelQuery when eager-loading is set.
	Edges        OtohaCatalogModelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OtohaCatalogModelEdges holds the relations/edges for other nodes in the graph.
type OtohaCatalogModelEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OtohaCatalogModelEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OtohaCatalogModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case otohacatalogmodel.FieldInputs, otohacatalogmodel.FieldReasoningLevels, otohacatalogmodel.FieldStrengths, otohacatalogmodel.FieldRoles, otohacatalogmodel.FieldUses:
			values[i] = new([]byte)
		case otohacatalogmodel.FieldEnabled, otohacatalogmodel.FieldTools:
			values[i] = new(sql.NullBool)
		case otohacatalogmodel.FieldID, otohacatalogmodel.FieldGroupID, otohacatalogmodel.FieldSortOrder, otohacatalogmodel.FieldContextTokens, otohacatalogmodel.FieldMaxOutputTokens:
			values[i] = new(sql.NullInt64)
		case otohacatalogmodel.FieldModelID, otohacatalogmodel.FieldName, otohacatalogmodel.FieldDescription, otohacatalogmodel.FieldDefaultReasoning, otohacatalogmodel.FieldSpeed, otohacatalogmodel.FieldComplexity, otohacatalogmodel.FieldProfileSource, otohacatalogmodel.FieldCostTier:
			values[i] = new(sql.NullString)
		case otohacatalogmodel.FieldCreatedAt, otohacatalogmodel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OtohaCatalogModel fields.
func (_m *OtohaCatalogModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case otohacatalogmodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case otohacatalogmodel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case otohacatalogmodel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case otohacatalogmodel.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case otohacatalogmodel.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case otohacatalogmodel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case otohacatalogmodel.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case otohacatalogmodel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case otohacatalogmodel.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case otohacatalogmodel.FieldInputs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field inputs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Inputs); err != nil {
					return fmt.Errorf("unmarshal field inputs: %w", err)
				}
			}
		case otohacatalogmodel.FieldTools:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tools", values[i])
			} else if value.Valid {
				_m.Tools = value.Bool
			}
		case otohacatalogmodel.FieldContextTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field context_tokens", values[i])
			} else if value.Valid {
				_m.ContextTokens = int(value.Int64)
			}
		case otohacatalogmodel.FieldMaxOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_output_tokens", values[i])
			} else if value.Valid {
				_m.MaxOutputTokens = int(value.Int64)
			}
		case otohacatalogmodel.FieldReasoningLevels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_levels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ReasoningLevels); err != nil {
					return fmt.Errorf("unmarshal field reasoning_levels: %w", err)
				}
			}
		case otohacatalogmodel.FieldDefaultReasoning:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_reasoning", values[i])
			} else if value.Valid {
				_m.DefaultReasoning = value.String
			}
		case otohacatalogmodel.FieldSpeed:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field speed", values[i])
			} else if value.Valid {
				_m.Speed = value.String
			}
		case otohacatalogmodel.FieldStrengths:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field strengths", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Strengths); err != nil {
					return fmt.Errorf("unmarshal field strengths: %w", err)
				}
			}
		case otohacatalogmodel.FieldComplexity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field complexity", values[i])
			} else if value.Valid {
				_m.Complexity = value.String
			}
		case otohacatalogmodel.FieldRoles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field roles", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Roles); err != nil {
					return fmt.Errorf("unmarshal field roles: %w", err)
				}
			}
		case otohacatalogmodel.FieldUses:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field uses", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Uses); err != nil {
					return fmt.Errorf("unmarshal field uses: %w", err)
				}
			}
		case otohacatalogmodel.FieldProfileSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_source", values[i])
			} else if value.Valid {
				_m.ProfileSource = value.String
			}
		case otohacatalogmodel.FieldCostTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cost_tier", values[i])
			} else if value.Valid {
				_m.CostTier = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OtohaCatalogModel.
// This includes values selected through modifiers, order, etc.
func (_m *OtohaCatalogModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the OtohaCatalogModel entity.
func (_m *OtohaCatalogModel) QueryGroup() *GroupQuery {
	return NewOtohaCatalogModelClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this OtohaCatalogModel.
// Note that you need to call OtohaCatalogModel.Unwrap() before calling this method if this OtohaCatalogModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OtohaCatalogModel) Update() *OtohaCatalogModelUpdateOne {
	return NewOtohaCatalogModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OtohaCatalogModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OtohaCatalogModel) Unwrap() *OtohaCatalogModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OtohaCatalogModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OtohaCatalogModel) String() string {
	var builder strings.Builder
	builder.WriteString("OtohaCatalogModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("inputs=")
	builder.WriteString(fmt.Sprintf("%v", _m.Inputs))
	builder.WriteString(", ")
	builder.WriteString("tools=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tools))
	builder.WriteString(", ")
	builder.WriteString("context_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContextTokens))
	builder.WriteString(", ")
	builder.WriteString("max_output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxOutputTokens))
	builder.WriteString(", ")
	builder.WriteString("reasoning_levels=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReasoningLevels))
	builder.WriteString(", ")
	builder.WriteString("default_reasoning=")
	builder.WriteString(_m.DefaultReasoning)
	builder.WriteString(", ")
	builder.WriteString("speed=")
	builder.WriteString(_m.Speed)
	builder.WriteString(", ")
	builder.WriteString("strengths=")
	builder.WriteString(fmt.Sprintf("%v", _m.Strengths))
	builder.WriteString(", ")
	builder.WriteString("complexity=")
	builder.WriteString(_m.Complexity)
	builder.WriteString(", ")
	builder.WriteString("roles=")
	builder.WriteString(fmt.Sprintf("%v", _m.Roles))
	builder.WriteString(", ")
	builder.WriteString("uses=")
	builder.WriteString(fmt.Sprintf("%v", _m.Uses))
	builder.WriteString(", ")
	builder.WriteString("profile_source=")
	builder.WriteString(_m.ProfileSource)
	builder.WriteString(", ")
	builder.WriteString("cost_tier=")
	builder.WriteString(_m.CostTier)
	builder.WriteByte(')')
	return builder.String()
}

// OtohaCatalogModels is a parsable slice of OtohaCatalogModel.
type OtohaCatalogModels []*OtohaCatalogModel
