// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/otohacatalogmodel"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OtohaCatalogModelDelete is the builder for deleting a OtohaCatalogModel entity.
type OtohaCatalogModelDelete struct {
	config
	hooks    []Hook
	mutation *OtohaCatalogModelMutation
}

// Where appends a list predicates to the OtohaCatalogModelDelete builder.
func (_d *OtohaCatalogModelDelete) Where(ps ...predicate.OtohaCatalogModel) *OtohaCatalogModelDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OtohaCatalogModelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OtohaCatalogModelDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OtohaCatalogModelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(otohacatalogmodel.Table, sqlgraph.NewFieldSpec(otohacatalogmodel.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OtohaCatalogModelDeleteOne is the builder for deleting a single OtohaCatalogModel entity.
type OtohaCatalogModelDeleteOne struct {
	_d *OtohaCatalogModelDelete
}

// Where appends a list predicates to the OtohaCatalogModelDelete builder.
func (_d *OtohaCatalogModelDeleteOne) Where(ps ...predicate.OtohaCatalogModel) *OtohaCatalogModelDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OtohaCatalogModelDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{otohacatalogmodel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OtohaCatalogModelDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
