// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/otohacatalogmodel"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OtohaCatalogModelUpdate is the builder for updating OtohaCatalogModel entities.
type OtohaCatalogModelUpdate struct {
	config
	hooks    []Hook
	mutation *OtohaCatalogModelMutation
}

// Where appends a list predicates to the OtohaCatalogModelUpdate builder.
func (_u *OtohaCatalogModelUpdate) Where(ps ...predicate.OtohaCatalogModel) *OtohaCatalogModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OtohaCatalogModelUpdate) SetUpdatedAt(v time.Time) *OtohaCatalogModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OtohaCatalogModelUpdate) SetGroupID(v int64) *OtohaCatalogModelUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableGroupID(v *int64) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *OtohaCatalogModelUpdate) SetModelID(v string) *OtohaCatalogModelUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableModelID(v *string) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OtohaCatalogModelUpdate) SetName(v string) *OtohaCatalogModelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableName(v *string) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OtohaCatalogModelUpdate) SetDescription(v string) *OtohaCatalogModelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableDescription(v *string) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *OtohaCatalogModelUpdate) SetEnabled(v bool) *OtohaCatalogModelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableEnabled(v *bool) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *OtohaCatalogModelUpdate) SetSortOrder(v int) *OtohaCatalogModelUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableSortOrder(v *int) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *OtohaCatalogModelUpdate) AddSortOrder(v int) *OtohaCatalogModelUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetInputs sets the "inputs" field.
func (_u *OtohaCatalogModelUpdate) SetInputs(v []string) *OtohaCatalogModelUpdate {
	_u.mutation.SetInputs(v)
	return _u
}

// AppendInputs appends value to the "inputs" field.
func (_u *OtohaCatalogModelUpdate) AppendInputs(v []string) *OtohaCatalogModelUpdate {
	_u.mutation.AppendInputs(v)
	return _u
}

// ClearInputs clears the value of the "inputs" field.
func (_u *OtohaCatalogModelUpdate) ClearInputs() *OtohaCatalogModelUpdate {
	_u.mutation.ClearInputs()
	return _u
}

// SetTools sets the "tools" field.
func (_u *OtohaCatalogModelUpdate) SetTools(v bool) *OtohaCatalogModelUpdate {
	_u.mutation.SetTools(v)
	return _u
}

// SetNillableTools sets the "tools" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableTools(v *bool) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetTools(*v)
	}
	return _u
}

// SetContextTokens sets the "context_tokens" field.
func (_u *OtohaCatalogModelUpdate) SetContextTokens(v int) *OtohaCatalogModelUpdate {
	_u.mutation.ResetContextTokens()
	_u.mutation.SetContextTokens(v)
	return _u
}

// SetNillableContextTokens sets the "context_tokens" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableContextTokens(v *int) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetContextTokens(*v)
	}
	return _u
}

// AddContextTokens adds value to the "context_tokens" field.
func (_u *OtohaCatalogModelUpdate) AddContextTokens(v int) *OtohaCatalogModelUpdate {
	_u.mutation.AddContextTokens(v)
	return _u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_u *OtohaCatalogModelUpdate) SetMaxOutputTokens(v int) *OtohaCatalogModelUpdate {
	_u.mutation.ResetMaxOutputTokens()
	_u.mutation.SetMaxOutputTokens(v)
	return _u
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableMaxOutputTokens(v *int) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetMaxOutputTokens(*v)
	}
	return _u
}

// AddMaxOutputTokens adds value to the "max_output_tokens" field.
func (_u *OtohaCatalogModelUpdate) AddMaxOutputTokens(v int) *OtohaCatalogModelUpdate {
	_u.mutation.AddMaxOutputTokens(v)
	return _u
}

// SetReasoningLevels sets the "reasoning_levels" field.
func (_u *OtohaCatalogModelUpdate) SetReasoningLevels(v []string) *OtohaCatalogModelUpdate {
	_u.mutation.SetReasoningLevels(v)
	return _u
}

// AppendReasoningLevels appends value to the "reasoning_levels" field.
func (_u *OtohaCatalogModelUpdate) AppendReasoningLevels(v []string) *OtohaCatalogModelUpdate {
	_u.mutation.AppendReasoningLevels(v)
	return _u
}

// ClearReasoningLevels clears the value of the "reasoning_levels" field.
func (_u *OtohaCatalogModelUpdate) ClearReasoningLevels() *OtohaCatalogModelUpdate {
	_u.mutation.ClearReasoningLevels()
	return _u
}

// SetDefaultReasoning sets the "default_reasoning" field.
func (_u *OtohaCatalogModelUpdate) SetDefaultReasoning(v string) *OtohaCatalogModelUpdate {
	_u.mutation.SetDefaultReasoning(v)
	return _u
}

// SetNillableDefaultReasoning sets the "default_reasoning" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableDefaultReasoning(v *string) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetDefaultReasoning(*v)
	}
	return _u
}

// SetSpeed sets the "speed" field.
func (_u *OtohaCatalogModelUpdate) SetSpeed(v string) *OtohaCatalogModelUpdate {
	_u.mutation.SetSpeed(v)
	return _u
}

// SetNillableSpeed sets the "speed" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableSpeed(v *string) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetSpeed(*v)
	}
	return _u
}

// SetStrengths sets the "strengths" field.
func (_u *OtohaCatalogModelUpdate) SetStrengths(v map[string]string) *OtohaCatalogModelUpdate {
	_u.mutation.SetStrengths(v)
	return _u
}

// ClearStrengths clears the value of the "strengths" field.
func (_u *OtohaCatalogModelUpdate) ClearStrengths() *OtohaCatalogModelUpdate {
	_u.mutation.ClearStrengths()
	return _u
}

// SetComplexity sets the "complexity" field.
func (_u *OtohaCatalogModelUpdate) SetComplexity(v string) *OtohaCatalogModelUpdate {
	_u.mutation.SetComplexity(v)
	return _u
}

// SetNillableComplexity sets the "complexity" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableComplexity(v *string) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetComplexity(*v)
	}
	return _u
}

// SetRoles sets the "roles" field.
func (_u *OtohaCatalogModelUpdate) SetRoles(v []string) *OtohaCatalogModelUpdate {
	_u.mutation.SetRoles(v)
	return _u
}

// AppendRoles appends value to the "roles" field.
func (_u *OtohaCatalogModelUpdate) AppendRoles(v []string) *OtohaCatalogModelUpdate {
	_u.mutation.AppendRoles(v)
	return _u
}

// ClearRoles clears the value of the "roles" field.
func (_u *OtohaCatalogModelUpdate) ClearRoles() *OtohaCatalogModelUpdate {
	_u.mutation.ClearRoles()
	return _u
}

// SetUses sets the "uses" field.
func (_u *OtohaCatalogModelUpdate) SetUses(v []string) *OtohaCatalogModelUpdate {
	_u.mutation.SetUses(v)
	return _u
}

// AppendUses appends value to the "uses" field.
func (_u *OtohaCatalogModelUpdate) AppendUses(v []string) *OtohaCatalogModelUpdate {
	_u.mutation.AppendUses(v)
	return _u
}

// ClearUses clears the value of the "uses" field.
func (_u *OtohaCatalogModelUpdate) ClearUses() *OtohaCatalogModelUpdate {
	_u.mutation.ClearUses()
	return _u
}

// SetProfileSource sets the "profile_source" field.
func (_u *OtohaCatalogModelUpdate) SetProfileSource(v string) *OtohaCatalogModelUpdate {
	_u.mutation.SetProfileSource(v)
	return _u
}

// SetNillableProfileSource sets the "profile_source" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableProfileSource(v *string) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetProfileSource(*v)
	}
	return _u
}

// SetCostTier sets the "cost_tier" field.
func (_u *OtohaCatalogModelUpdate) SetCostTier(v string) *OtohaCatalogModelUpdate {
	_u.mutation.SetCostTier(v)
	return _u
}

// SetNillableCostTier sets the "cost_tier" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdate) SetNillableCostTier(v *string) *OtohaCatalogModelUpdate {
	if v != nil {
		_u.SetCostTier(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OtohaCatalogModelUpdate) SetGroup(v *Group) *OtohaCatalogModelUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the OtohaCatalogModelMutation object of the builder.
func (_u *OtohaCatalogModelUpdate) Mutation() *OtohaCatalogModelMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OtohaCatalogModelUpdate) ClearGroup() *OtohaCatalogModelUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OtohaCatalogModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OtohaCatalogModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OtohaCatalogModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OtohaCatalogModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OtohaCatalogModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := otohacatalogmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OtohaCatalogModelUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := otohacatalogmodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := otohacatalogmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultReasoning(); ok {
		if err := otohacatalogmodel.DefaultReasoningValidator(v); err != nil {
			return &ValidationError{Name: "default_reasoning", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.default_reasoning": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Speed(); ok {
		if err := otohacatalogmodel.SpeedValidator(v); err != nil {
			return &ValidationError{Name: "speed", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.speed": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Complexity(); ok {
		if err := otohacatalogmodel.ComplexityValidator(v); err != nil {
			return &ValidationError{Name: "complexity", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.complexity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProfileSource(); ok {
		if err := otohacatalogmodel.ProfileSourceValidator(v); err != nil {
			return &ValidationError{Name: "profile_source", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.profile_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostTier(); ok {
		if err := otohacatalogmodel.CostTierValidator(v); err != nil {
			return &ValidationError{Name: "cost_tier", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.cost_tier": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OtohaCatalogModel.group"`)
	}
	return nil
}

func (_u *OtohaCatalogModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(otohacatalogmodel.Table, otohacatalogmodel.Columns, sqlgraph.NewFieldSpec(otohacatalogmodel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(otohacatalogmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(otohacatalogmodel.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(otohacatalogmodel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(otohacatalogmodel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(otohacatalogmodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(otohacatalogmodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(otohacatalogmodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Inputs(); ok {
		_spec.SetField(otohacatalogmodel.FieldInputs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInputs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, otohacatalogmodel.FieldInputs, value)
		})
	}
	if _u.mutation.InputsCleared() {
		_spec.ClearField(otohacatalogmodel.FieldInputs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tools(); ok {
		_spec.SetField(otohacatalogmodel.FieldTools, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContextTokens(); ok {
		_spec.SetField(otohacatalogmodel.FieldContextTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContextTokens(); ok {
		_spec.AddField(otohacatalogmodel.FieldContextTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxOutputTokens(); ok {
		_spec.SetField(otohacatalogmodel.FieldMaxOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOutputTokens(); ok {
		_spec.AddField(otohacatalogmodel.FieldMaxOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReasoningLevels(); ok {
		_spec.SetField(otohacatalogmodel.FieldReasoningLevels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReasoningLevels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, otohacatalogmodel.FieldReasoningLevels, value)
		})
	}
	if _u.mutation.ReasoningLevelsCleared() {
		_spec.ClearField(otohacatalogmodel.FieldReasoningLevels, field.TypeJSON)
	}
	if value, ok := _u.mutation.DefaultReasoning(); ok {
		_spec.SetField(otohacatalogmodel.FieldDefaultReasoning, field.TypeString, value)
	}
	if value, ok := _u.mutation.Speed(); ok {
		_spec.SetField(otohacatalogmodel.FieldSpeed, field.TypeString, value)
	}
	if value, ok := _u.mutation.Strengths(); ok {
		_spec.SetField(otohacatalogmodel.FieldStrengths, field.TypeJSON, value)
	}
	if _u.mutation.StrengthsCleared() {
		_spec.ClearField(otohacatalogmodel.FieldStrengths, field.TypeJSON)
	}
	if value, ok := _u.mutation.Complexity(); ok {
		_spec.SetField(otohacatalogmodel.FieldComplexity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Roles(); ok {
		_spec.SetField(otohacatalogmodel.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, otohacatalogmodel.FieldRoles, value)
		})
	}
	if _u.mutation.RolesCleared() {
		_spec.ClearField(otohacatalogmodel.FieldRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.Uses(); ok {
		_spec.SetField(otohacatalogmodel.FieldUses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, otohacatalogmodel.FieldUses, value)
		})
	}
	if _u.mutation.UsesCleared() {
		_spec.ClearField(otohacatalogmodel.FieldUses, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProfileSource(); ok {
		_spec.SetField(otohacatalogmodel.FieldProfileSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostTier(); ok {
		_spec.SetField(otohacatalogmodel.FieldCostTier, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   otohacatalogmodel.GroupTable,
			Columns: []string{otohacatalogmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   otohacatalogmodel.GroupTable,
			Columns: []string{otohacatalogmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otohacatalogmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OtohaCatalogModelUpdateOne is the builder for updating a single OtohaCatalogModel entity.
type OtohaCatalogModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OtohaCatalogModelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OtohaCatalogModelUpdateOne) SetUpdatedAt(v time.Time) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OtohaCatalogModelUpdateOne) SetGroupID(v int64) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableGroupID(v *int64) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *OtohaCatalogModelUpdateOne) SetModelID(v string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableModelID(v *string) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OtohaCatalogModelUpdateOne) SetName(v string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableName(v *string) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OtohaCatalogModelUpdateOne) SetDescription(v string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableDescription(v *string) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *OtohaCatalogModelUpdateOne) SetEnabled(v bool) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableEnabled(v *bool) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *OtohaCatalogModelUpdateOne) SetSortOrder(v int) *OtohaCatalogModelUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableSortOrder(v *int) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *OtohaCatalogModelUpdateOne) AddSortOrder(v int) *OtohaCatalogModelUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetInputs sets the "inputs" field.
func (_u *OtohaCatalogModelUpdateOne) SetInputs(v []string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetInputs(v)
	return _u
}

// AppendInputs appends value to the "inputs" field.
func (_u *OtohaCatalogModelUpdateOne) AppendInputs(v []string) *OtohaCatalogModelUpdateOne {
	_u.mutation.AppendInputs(v)
	return _u
}

// ClearInputs clears the value of the "inputs" field.
func (_u *OtohaCatalogModelUpdateOne) ClearInputs() *OtohaCatalogModelUpdateOne {
	_u.mutation.ClearInputs()
	return _u
}

// SetTools sets the "tools" field.
func (_u *OtohaCatalogModelUpdateOne) SetTools(v bool) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetTools(v)
	return _u
}

// SetNillableTools sets the "tools" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableTools(v *bool) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetTools(*v)
	}
	return _u
}

// SetContextTokens sets the "context_tokens" field.
func (_u *OtohaCatalogModelUpdateOne) SetContextTokens(v int) *OtohaCatalogModelUpdateOne {
	_u.mutation.ResetContextTokens()
	_u.mutation.SetContextTokens(v)
	return _u
}

// SetNillableContextTokens sets the "context_tokens" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableContextTokens(v *int) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetContextTokens(*v)
	}
	return _u
}

// AddContextTokens adds value to the "context_tokens" field.
func (_u *OtohaCatalogModelUpdateOne) AddContextTokens(v int) *OtohaCatalogModelUpdateOne {
	_u.mutation.AddContextTokens(v)
	return _u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_u *OtohaCatalogModelUpdateOne) SetMaxOutputTokens(v int) *OtohaCatalogModelUpdateOne {
	_u.mutation.ResetMaxOutputTokens()
	_u.mutation.SetMaxOutputTokens(v)
	return _u
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableMaxOutputTokens(v *int) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetMaxOutputTokens(*v)
	}
	return _u
}

// AddMaxOutputTokens adds value to the "max_output_tokens" field.
func (_u *OtohaCatalogModelUpdateOne) AddMaxOutputTokens(v int) *OtohaCatalogModelUpdateOne {
	_u.mutation.AddMaxOutputTokens(v)
	return _u
}

// SetReasoningLevels sets the "reasoning_levels" field.
func (_u *OtohaCatalogModelUpdateOne) SetReasoningLevels(v []string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetReasoningLevels(v)
	return _u
}

// AppendReasoningLevels appends value to the "reasoning_levels" field.
func (_u *OtohaCatalogModelUpdateOne) AppendReasoningLevels(v []string) *OtohaCatalogModelUpdateOne {
	_u.mutation.AppendReasoningLevels(v)
	return _u
}

// ClearReasoningLevels clears the value of the "reasoning_levels" field.
func (_u *OtohaCatalogModelUpdateOne) ClearReasoningLevels() *OtohaCatalogModelUpdateOne {
	_u.mutation.ClearReasoningLevels()
	return _u
}

// SetDefaultReasoning sets the "default_reasoning" field.
func (_u *OtohaCatalogModelUpdateOne) SetDefaultReasoning(v string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetDefaultReasoning(v)
	return _u
}

// SetNillableDefaultReasoning sets the "default_reasoning" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableDefaultReasoning(v *string) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetDefaultReasoning(*v)
	}
	return _u
}

// SetSpeed sets the "speed" field.
func (_u *OtohaCatalogModelUpdateOne) SetSpeed(v string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetSpeed(v)
	return _u
}

// SetNillableSpeed sets the "speed" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableSpeed(v *string) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetSpeed(*v)
	}
	return _u
}

// SetStrengths sets the "strengths" field.
func (_u *OtohaCatalogModelUpdateOne) SetStrengths(v map[string]string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetStrengths(v)
	return _u
}

// ClearStrengths clears the value of the "strengths" field.
func (_u *OtohaCatalogModelUpdateOne) ClearStrengths() *OtohaCatalogModelUpdateOne {
	_u.mutation.ClearStrengths()
	return _u
}

// SetComplexity sets the "complexity" field.
func (_u *OtohaCatalogModelUpdateOne) SetComplexity(v string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetComplexity(v)
	return _u
}

// SetNillableComplexity sets the "complexity" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableComplexity(v *string) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetComplexity(*v)
	}
	return _u
}

// SetRoles sets the "roles" field.
func (_u *OtohaCatalogModelUpdateOne) SetRoles(v []string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetRoles(v)
	return _u
}

// AppendRoles appends value to the "roles" field.
func (_u *OtohaCatalogModelUpdateOne) AppendRoles(v []string) *OtohaCatalogModelUpdateOne {
	_u.mutation.AppendRoles(v)
	return _u
}

// ClearRoles clears the value of the "roles" field.
func (_u *OtohaCatalogModelUpdateOne) ClearRoles() *OtohaCatalogModelUpdateOne {
	_u.mutation.ClearRoles()
	return _u
}

// SetUses sets the "uses" field.
func (_u *OtohaCatalogModelUpdateOne) SetUses(v []string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetUses(v)
	return _u
}

// AppendUses appends value to the "uses" field.
func (_u *OtohaCatalogModelUpdateOne) AppendUses(v []string) *OtohaCatalogModelUpdateOne {
	_u.mutation.AppendUses(v)
	return _u
}

// ClearUses clears the value of the "uses" field.
func (_u *OtohaCatalogModelUpdateOne) ClearUses() *OtohaCatalogModelUpdateOne {
	_u.mutation.ClearUses()
	return _u
}

// SetProfileSource sets the "profile_source" field.
func (_u *OtohaCatalogModelUpdateOne) SetProfileSource(v string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetProfileSource(v)
	return _u
}

// SetNillableProfileSource sets the "profile_source" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableProfileSource(v *string) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetProfileSource(*v)
	}
	return _u
}

// SetCostTier sets the "cost_tier" field.
func (_u *OtohaCatalogModelUpdateOne) SetCostTier(v string) *OtohaCatalogModelUpdateOne {
	_u.mutation.SetCostTier(v)
	return _u
}

// SetNillableCostTier sets the "cost_tier" field if the given value is not nil.
func (_u *OtohaCatalogModelUpdateOne) SetNillableCostTier(v *string) *OtohaCatalogModelUpdateOne {
	if v != nil {
		_u.SetCostTier(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OtohaCatalogModelUpdateOne) SetGroup(v *Group) *OtohaCatalogModelUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the OtohaCatalogModelMutation object of the builder.
func (_u *OtohaCatalogModelUpdateOne) Mutation() *OtohaCatalogModelMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OtohaCatalogModelUpdateOne) ClearGroup() *OtohaCatalogModelUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the OtohaCatalogModelUpdate builder.
func (_u *OtohaCatalogModelUpdateOne) Where(ps ...predicate.OtohaCatalogModel) *OtohaCatalogModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OtohaCatalogModelUpdateOne) Select(field string, fields ...string) *OtohaCatalogModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OtohaCatalogModel entity.
func (_u *OtohaCatalogModelUpdateOne) Save(ctx context.Context) (*OtohaCatalogModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OtohaCatalogModelUpdateOne) SaveX(ctx context.Context) *OtohaCatalogModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OtohaCatalogModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OtohaCatalogModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OtohaCatalogModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := otohacatalogmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OtohaCatalogModelUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := otohacatalogmodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := otohacatalogmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultReasoning(); ok {
		if err := otohacatalogmodel.DefaultReasoningValidator(v); err != nil {
			return &ValidationError{Name: "default_reasoning", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.default_reasoning": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Speed(); ok {
		if err := otohacatalogmodel.SpeedValidator(v); err != nil {
			return &ValidationError{Name: "speed", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.speed": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Complexity(); ok {
		if err := otohacatalogmodel.ComplexityValidator(v); err != nil {
			return &ValidationError{Name: "complexity", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.complexity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProfileSource(); ok {
		if err := otohacatalogmodel.ProfileSourceValidator(v); err != nil {
			return &ValidationError{Name: "profile_source", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.profile_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostTier(); ok {
		if err := otohacatalogmodel.CostTierValidator(v); err != nil {
			return &ValidationError{Name: "cost_tier", err: fmt.Errorf(`ent: validator failed for field "OtohaCatalogModel.cost_tier": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OtohaCatalogModel.group"`)
	}
	return nil
}

func (_u *OtohaCatalogModelUpdateOne) sqlSave(ctx context.Context) (_node *OtohaCatalogModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(otohacatalogmodel.Table, otohacatalogmodel.Columns, sqlgraph.NewFieldSpec(otohacatalogmodel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OtohaCatalogModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otohacatalogmodel.FieldID)
		for _, f := range fields {
			if !otohacatalogmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != otohacatalogmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(otohacatalogmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(otohacatalogmodel.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(otohacatalogmodel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(otohacatalogmodel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(otohacatalogmodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(otohacatalogmodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(otohacatalogmodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Inputs(); ok {
		_spec.SetField(otohacatalogmodel.FieldInputs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInputs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, otohacatalogmodel.FieldInputs, value)
		})
	}
	if _u.mutation.InputsCleared() {
		_spec.ClearField(otohacatalogmodel.FieldInputs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tools(); ok {
		_spec.SetField(otohacatalogmodel.FieldTools, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContextTokens(); ok {
		_spec.SetField(otohacatalogmodel.FieldContextTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContextTokens(); ok {
		_spec.AddField(otohacatalogmodel.FieldContextTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxOutputTokens(); ok {
		_spec.SetField(otohacatalogmodel.FieldMaxOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOutputTokens(); ok {
		_spec.AddField(otohacatalogmodel.FieldMaxOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReasoningLevels(); ok {
		_spec.SetField(otohacatalogmodel.FieldReasoningLevels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReasoningLevels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, otohacatalogmodel.FieldReasoningLevels, value)
		})
	}
	if _u.mutation.ReasoningLevelsCleared() {
		_spec.ClearField(otohacatalogmodel.FieldReasoningLevels, field.TypeJSON)
	}
	if value, ok := _u.mutation.DefaultReasoning(); ok {
		_spec.SetField(otohacatalogmodel.FieldDefaultReasoning, field.TypeString, value)
	}
	if value, ok := _u.mutation.Speed(); ok {
		_spec.SetField(otohacatalogmodel.FieldSpeed, field.TypeString, value)
	}
	if value, ok := _u.mutation.Strengths(); ok {
		_spec.SetField(otohacatalogmodel.FieldStrengths, field.TypeJSON, value)
	}
	if _u.mutation.StrengthsCleared() {
		_spec.ClearField(otohacatalogmodel.FieldStrengths, field.TypeJSON)
	}
	if value, ok := _u.mutation.Complexity(); ok {
		_spec.SetField(otohacatalogmodel.FieldComplexity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Roles(); ok {
		_spec.SetField(otohacatalogmodel.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, otohacatalogmodel.FieldRoles, value)
		})
	}
	if _u.mutation.RolesCleared() {
		_spec.ClearField(otohacatalogmodel.FieldRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.Uses(); ok {
		_spec.SetField(otohacatalogmodel.FieldUses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, otohacatalogmodel.FieldUses, value)
		})
	}
	if _u.mutation.UsesCleared() {
		_spec.ClearField(otohacatalogmodel.FieldUses, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProfileSource(); ok {
		_spec.SetField(otohacatalogmodel.FieldProfileSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostTier(); ok {
		_spec.SetField(otohacatalogmodel.FieldCostTier, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   otohacatalogmodel.GroupTable,
			Columns: []string{otohacatalogmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   otohacatalogmodel.GroupTable,
			Columns: []string{otohacatalogmodel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OtohaCatalogModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otohacatalogmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
