// Code generated by ent, DO NOT EDIT.

package otohacatalogmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the otohacatalogmodel type in the database.
	Label = "otoha_catalog_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldInputs holds the string denoting the inputs field in the database.
	FieldInputs = "inputs"
	// FieldTools holds the string denoting the tools field in the database.
	FieldTools = "tools"
	// FieldContextTokens holds the string denoting the context_tokens field in the database.
	FieldContextTokens = "context_tokens"
	// FieldMaxOutputTokens holds the string denoting the max_output_tokens field in the database.
	FieldMaxOutputTokens = "max_output_tokens"
	// FieldReasoningLevels holds the string denoting the reasoning_levels field in the database.
	FieldReasoningLevels = "reasoning_levels"
	// FieldDefaultReasoning holds the string denoting the default_reasoning field in the database.
	FieldDefaultReasoning = "default_reasoning"
	// FieldSpeed holds the string denoting the speed field in the database.
	FieldSpeed = "speed"
	// FieldStrengths holds the string denoting the strengths field in the database.
	FieldStrengths = "strengths"
	// FieldComplexity holds the string denoting the complexity field in the database.
	FieldComplexity = "complexity"
	// FieldRoles holds the string denoting the roles field in the database.
	FieldRoles = "roles"
	// FieldUses holds the string denoting the uses field in the database.
	FieldUses = "uses"
	// FieldProfileSource holds the string denoting the profile_source field in the database.
	FieldProfileSource = "profile_source"
	// FieldCostTier holds the string denoting the cost_tier field in the database.
	FieldCostTier = "cost_tier"
	// FieldAPI holds the string denoting the api field in the database.
	FieldAPI = "api"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the otohacatalogmodel in the database.
	Table = "otoha_catalog_models"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "otoha_catalog_models"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for otohacatalogmodel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGroupID,
	FieldModelID,
	FieldName,
	FieldDescription,
	FieldEnabled,
	FieldSortOrder,
	FieldInputs,
	FieldTools,
	FieldContextTokens,
	FieldMaxOutputTokens,
	FieldReasoningLevels,
	FieldDefaultReasoning,
	FieldSpeed,
	FieldStrengths,
	FieldComplexity,
	FieldRoles,
	FieldUses,
	FieldProfileSource,
	FieldCostTier,
	FieldAPI,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	ModelIDValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultTools holds the default value on creation for the "tools" field.
	DefaultTools bool
	// DefaultContextTokens holds the default value on creation for the "context_tokens" field.
	DefaultContextTokens int
	// DefaultMaxOutputTokens holds the default value on creation for the "max_output_tokens" field.
	DefaultMaxOutputTokens int
	// DefaultDefaultReasoning holds the default value on creation for the "default_reasoning" field.
	DefaultDefaultReasoning string
	// DefaultReasoningValidator is a validator for the "default_reasoning" field. It is called by the builders before save.
	DefaultReasoningValidator func(string) error
	// DefaultSpeed holds the default value on creation for the "speed" field.
	DefaultSpeed string
	// SpeedValidator is a validator for the "speed" field. It is called by the builders before save.
	SpeedValidator func(string) error
	// DefaultComplexity holds the default value on creation for the "complexity" field.
	DefaultComplexity string
	// ComplexityValidator is a validator for the "complexity" field. It is called by the builders before save.
	ComplexityValidator func(string) error
	// DefaultProfileSource holds the default value on creation for the "profile_source" field.
	DefaultProfileSource string
	// ProfileSourceValidator is a validator for the "profile_source" field. It is called by the builders before save.
	ProfileSourceValidator func(string) error
	// DefaultCostTier holds the default value on creation for the "cost_tier" field.
	DefaultCostTier string
	// CostTierValidator is a validator for the "cost_tier" field. It is called by the builders before save.
	CostTierValidator func(string) error
	// DefaultAPI holds the default value on creation for the "api" field.
	DefaultAPI string
	// APIValidator is a validator for the "api" field. It is called by the builders before save.
	APIValidator func(string) error
)

// OrderOption defines the ordering options for the OtohaCatalogModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByTools orders the results by the tools field.
func ByTools(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTools, opts...).ToFunc()
}

// ByContextTokens orders the results by the context_tokens field.
func ByContextTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextTokens, opts...).ToFunc()
}

// ByMaxOutputTokens orders the results by the max_output_tokens field.
func ByMaxOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxOutputTokens, opts...).ToFunc()
}

// ByDefaultReasoning orders the results by the default_reasoning field.
func ByDefaultReasoning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultReasoning, opts...).ToFunc()
}

// BySpeed orders the results by the speed field.
func BySpeed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpeed, opts...).ToFunc()
}

// ByComplexity orders the results by the complexity field.
func ByComplexity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComplexity, opts...).ToFunc()
}

// ByProfileSource orders the results by the profile_source field.
func ByProfileSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileSource, opts...).ToFunc()
}

// ByCostTier orders the results by the cost_tier field.
func ByCostTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostTier, opts...).ToFunc()
}

// ByAPI orders the results by the api field.
func ByAPI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPI, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
