// Code generated by ent, DO NOT EDIT.

package otohacatalogmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldGroupID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldModelID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldDescription, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldSortOrder, v))
}

// Tools applies equality check predicate on the "tools" field. It's identical to ToolsEQ.
func Tools(v bool) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldTools, v))
}

// ContextTokens applies equality check predicate on the "context_tokens" field. It's identical to ContextTokensEQ.
func ContextTokens(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldContextTokens, v))
}

// MaxOutputTokens applies equality check predicate on the "max_output_tokens" field. It's identical to MaxOutputTokensEQ.
func MaxOutputTokens(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldMaxOutputTokens, v))
}

// DefaultReasoning applies equality check predicate on the "default_reasoning" field. It's identical to DefaultReasoningEQ.
func DefaultReasoning(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldDefaultReasoning, v))
}

// Speed applies equality check predicate on the "speed" field. It's identical to SpeedEQ.
func Speed(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldSpeed, v))
}

// Complexity applies equality check predicate on the "complexity" field. It's identical to ComplexityEQ.
func Complexity(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldComplexity, v))
}

// ProfileSource applies equality check predicate on the "profile_source" field. It's identical to ProfileSourceEQ.
func ProfileSource(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldProfileSource, v))
}

// CostTier applies equality check predicate on the "cost_tier" field. It's identical to CostTierEQ.
func CostTier(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldCostTier, v))
}

// API applies equality check predicate on the "api" field. It's identical to APIEQ.
func API(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldAPI, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldGroupID, vs...))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldModelID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldDescription, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldSortOrder, v))
}

// InputsIsNil applies the IsNil predicate on the "inputs" field.
func InputsIsNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIsNull(FieldInputs))
}

// InputsNotNil applies the NotNil predicate on the "inputs" field.
func InputsNotNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotNull(FieldInputs))
}

// ToolsEQ applies the EQ predicate on the "tools" field.
func ToolsEQ(v bool) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldTools, v))
}

// ToolsNEQ applies the NEQ predicate on the "tools" field.
func ToolsNEQ(v bool) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldTools, v))
}

// ContextTokensEQ applies the EQ predicate on the "context_tokens" field.
func ContextTokensEQ(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldContextTokens, v))
}

// ContextTokensNEQ applies the NEQ predicate on the "context_tokens" field.
func ContextTokensNEQ(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldContextTokens, v))
}

// ContextTokensIn applies the In predicate on the "context_tokens" field.
func ContextTokensIn(vs ...int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldContextTokens, vs...))
}

// ContextTokensNotIn applies the NotIn predicate on the "context_tokens" field.
func ContextTokensNotIn(vs ...int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldContextTokens, vs...))
}

// ContextTokensGT applies the GT predicate on the "context_tokens" field.
func ContextTokensGT(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldContextTokens, v))
}

// ContextTokensGTE applies the GTE predicate on the "context_tokens" field.
func ContextTokensGTE(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldContextTokens, v))
}

// ContextTokensLT applies the LT predicate on the "context_tokens" field.
func ContextTokensLT(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldContextTokens, v))
}

// ContextTokensLTE applies the LTE predicate on the "context_tokens" field.
func ContextTokensLTE(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldContextTokens, v))
}

// MaxOutputTokensEQ applies the EQ predicate on the "max_output_tokens" field.
func MaxOutputTokensEQ(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldMaxOutputTokens, v))
}

// MaxOutputTokensNEQ applies the NEQ predicate on the "max_output_tokens" field.
func MaxOutputTokensNEQ(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldMaxOutputTokens, v))
}

// MaxOutputTokensIn applies the In predicate on the "max_output_tokens" field.
func MaxOutputTokensIn(vs ...int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldMaxOutputTokens, vs...))
}

// MaxOutputTokensNotIn applies the NotIn predicate on the "max_output_tokens" field.
func MaxOutputTokensNotIn(vs ...int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldMaxOutputTokens, vs...))
}

// MaxOutputTokensGT applies the GT predicate on the "max_output_tokens" field.
func MaxOutputTokensGT(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldMaxOutputTokens, v))
}

// MaxOutputTokensGTE applies the GTE predicate on the "max_output_tokens" field.
func MaxOutputTokensGTE(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldMaxOutputTokens, v))
}

// MaxOutputTokensLT applies the LT predicate on the "max_output_tokens" field.
func MaxOutputTokensLT(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldMaxOutputTokens, v))
}

// MaxOutputTokensLTE applies the LTE predicate on the "max_output_tokens" field.
func MaxOutputTokensLTE(v int) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldMaxOutputTokens, v))
}

// ReasoningLevelsIsNil applies the IsNil predicate on the "reasoning_levels" field.
func ReasoningLevelsIsNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIsNull(FieldReasoningLevels))
}

// ReasoningLevelsNotNil applies the NotNil predicate on the "reasoning_levels" field.
func ReasoningLevelsNotNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotNull(FieldReasoningLevels))
}

// DefaultReasoningEQ applies the EQ predicate on the "default_reasoning" field.
func DefaultReasoningEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldDefaultReasoning, v))
}

// DefaultReasoningNEQ applies the NEQ predicate on the "default_reasoning" field.
func DefaultReasoningNEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldDefaultReasoning, v))
}

// DefaultReasoningIn applies the In predicate on the "default_reasoning" field.
func DefaultReasoningIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldDefaultReasoning, vs...))
}

// DefaultReasoningNotIn applies the NotIn predicate on the "default_reasoning" field.
func DefaultReasoningNotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldDefaultReasoning, vs...))
}

// DefaultReasoningGT applies the GT predicate on the "default_reasoning" field.
func DefaultReasoningGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldDefaultReasoning, v))
}

// DefaultReasoningGTE applies the GTE predicate on the "default_reasoning" field.
func DefaultReasoningGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldDefaultReasoning, v))
}

// DefaultReasoningLT applies the LT predicate on the "default_reasoning" field.
func DefaultReasoningLT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldDefaultReasoning, v))
}

// DefaultReasoningLTE applies the LTE predicate on the "default_reasoning" field.
func DefaultReasoningLTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldDefaultReasoning, v))
}

// DefaultReasoningContains applies the Contains predicate on the "default_reasoning" field.
func DefaultReasoningContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldDefaultReasoning, v))
}

// DefaultReasoningHasPrefix applies the HasPrefix predicate on the "default_reasoning" field.
func DefaultReasoningHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldDefaultReasoning, v))
}

// DefaultReasoningHasSuffix applies the HasSuffix predicate on the "default_reasoning" field.
func DefaultReasoningHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldDefaultReasoning, v))
}

// DefaultReasoningEqualFold applies the EqualFold predicate on the "default_reasoning" field.
func DefaultReasoningEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldDefaultReasoning, v))
}

// DefaultReasoningContainsFold applies the ContainsFold predicate on the "default_reasoning" field.
func DefaultReasoningContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldDefaultReasoning, v))
}

// SpeedEQ applies the EQ predicate on the "speed" field.
func SpeedEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldSpeed, v))
}

// SpeedNEQ applies the NEQ predicate on the "speed" field.
func SpeedNEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldSpeed, v))
}

// SpeedIn applies the In predicate on the "speed" field.
func SpeedIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldSpeed, vs...))
}

// SpeedNotIn applies the NotIn predicate on the "speed" field.
func SpeedNotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldSpeed, vs...))
}

// SpeedGT applies the GT predicate on the "speed" field.
func SpeedGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldSpeed, v))
}

// SpeedGTE applies the GTE predicate on the "speed" field.
func SpeedGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldSpeed, v))
}

// SpeedLT applies the LT predicate on the "speed" field.
func SpeedLT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldSpeed, v))
}

// SpeedLTE applies the LTE predicate on the "speed" field.
func SpeedLTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldSpeed, v))
}

// SpeedContains applies the Contains predicate on the "speed" field.
func SpeedContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldSpeed, v))
}

// SpeedHasPrefix applies the HasPrefix predicate on the "speed" field.
func SpeedHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldSpeed, v))
}

// SpeedHasSuffix applies the HasSuffix predicate on the "speed" field.
func SpeedHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldSpeed, v))
}

// SpeedEqualFold applies the EqualFold predicate on the "speed" field.
func SpeedEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldSpeed, v))
}

// SpeedContainsFold applies the ContainsFold predicate on the "speed" field.
func SpeedContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldSpeed, v))
}

// StrengthsIsNil applies the IsNil predicate on the "strengths" field.
func StrengthsIsNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIsNull(FieldStrengths))
}

// StrengthsNotNil applies the NotNil predicate on the "strengths" field.
func StrengthsNotNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotNull(FieldStrengths))
}

// ComplexityEQ applies the EQ predicate on the "complexity" field.
func ComplexityEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldComplexity, v))
}

// ComplexityNEQ applies the NEQ predicate on the "complexity" field.
func ComplexityNEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldComplexity, v))
}

// ComplexityIn applies the In predicate on the "complexity" field.
func ComplexityIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldComplexity, vs...))
}

// ComplexityNotIn applies the NotIn predicate on the "complexity" field.
func ComplexityNotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldComplexity, vs...))
}

// ComplexityGT applies the GT predicate on the "complexity" field.
func ComplexityGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldComplexity, v))
}

// ComplexityGTE applies the GTE predicate on the "complexity" field.
func ComplexityGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldComplexity, v))
}

// ComplexityLT applies the LT predicate on the "complexity" field.
func ComplexityLT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldComplexity, v))
}

// ComplexityLTE applies the LTE predicate on the "complexity" field.
func ComplexityLTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldComplexity, v))
}

// ComplexityContains applies the Contains predicate on the "complexity" field.
func ComplexityContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldComplexity, v))
}

// ComplexityHasPrefix applies the HasPrefix predicate on the "complexity" field.
func ComplexityHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldComplexity, v))
}

// ComplexityHasSuffix applies the HasSuffix predicate on the "complexity" field.
func ComplexityHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldComplexity, v))
}

// ComplexityEqualFold applies the EqualFold predicate on the "complexity" field.
func ComplexityEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldComplexity, v))
}

// ComplexityContainsFold applies the ContainsFold predicate on the "complexity" field.
func ComplexityContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldComplexity, v))
}

// RolesIsNil applies the IsNil predicate on the "roles" field.
func RolesIsNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIsNull(FieldRoles))
}

// RolesNotNil applies the NotNil predicate on the "roles" field.
func RolesNotNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotNull(FieldRoles))
}

// UsesIsNil applies the IsNil predicate on the "uses" field.
func UsesIsNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIsNull(FieldUses))
}

// UsesNotNil applies the NotNil predicate on the "uses" field.
func UsesNotNil() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotNull(FieldUses))
}

// ProfileSourceEQ applies the EQ predicate on the "profile_source" field.
func ProfileSourceEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldProfileSource, v))
}

// ProfileSourceNEQ applies the NEQ predicate on the "profile_source" field.
func ProfileSourceNEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldProfileSource, v))
}

// ProfileSourceIn applies the In predicate on the "profile_source" field.
func ProfileSourceIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldProfileSource, vs...))
}

// ProfileSourceNotIn applies the NotIn predicate on the "profile_source" field.
func ProfileSourceNotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldProfileSource, vs...))
}

// ProfileSourceGT applies the GT predicate on the "profile_source" field.
func ProfileSourceGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldProfileSource, v))
}

// ProfileSourceGTE applies the GTE predicate on the "profile_source" field.
func ProfileSourceGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldProfileSource, v))
}

// ProfileSourceLT applies the LT predicate on the "profile_source" field.
func ProfileSourceLT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldProfileSource, v))
}

// ProfileSourceLTE applies the LTE predicate on the "profile_source" field.
func ProfileSourceLTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldProfileSource, v))
}

// ProfileSourceContains applies the Contains predicate on the "profile_source" field.
func ProfileSourceContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldProfileSource, v))
}

// ProfileSourceHasPrefix applies the HasPrefix predicate on the "profile_source" field.
func ProfileSourceHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldProfileSource, v))
}

// ProfileSourceHasSuffix applies the HasSuffix predicate on the "profile_source" field.
func ProfileSourceHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldProfileSource, v))
}

// ProfileSourceEqualFold applies the EqualFold predicate on the "profile_source" field.
func ProfileSourceEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldProfileSource, v))
}

// ProfileSourceContainsFold applies the ContainsFold predicate on the "profile_source" field.
func ProfileSourceContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldProfileSource, v))
}

// CostTierEQ applies the EQ predicate on the "cost_tier" field.
func CostTierEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldCostTier, v))
}

// CostTierNEQ applies the NEQ predicate on the "cost_tier" field.
func CostTierNEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldCostTier, v))
}

// CostTierIn applies the In predicate on the "cost_tier" field.
func CostTierIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldCostTier, vs...))
}

// CostTierNotIn applies the NotIn predicate on the "cost_tier" field.
func CostTierNotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldCostTier, vs...))
}

// CostTierGT applies the GT predicate on the "cost_tier" field.
func CostTierGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldCostTier, v))
}

// CostTierGTE applies the GTE predicate on the "cost_tier" field.
func CostTierGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldCostTier, v))
}

// CostTierLT applies the LT predicate on the "cost_tier" field.
func CostTierLT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldCostTier, v))
}

// CostTierLTE applies the LTE predicate on the "cost_tier" field.
func CostTierLTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldCostTier, v))
}

// CostTierContains applies the Contains predicate on the "cost_tier" field.
func CostTierContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldCostTier, v))
}

// CostTierHasPrefix applies the HasPrefix predicate on the "cost_tier" field.
func CostTierHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldCostTier, v))
}

// CostTierHasSuffix applies the HasSuffix predicate on the "cost_tier" field.
func CostTierHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldCostTier, v))
}

// CostTierEqualFold applies the EqualFold predicate on the "cost_tier" field.
func CostTierEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldCostTier, v))
}

// CostTierContainsFold applies the ContainsFold predicate on the "cost_tier" field.
func CostTierContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldCostTier, v))
}

// APIEQ applies the EQ predicate on the "api" field.
func APIEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEQ(FieldAPI, v))
}

// APINEQ applies the NEQ predicate on the "api" field.
func APINEQ(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNEQ(FieldAPI, v))
}

// APIIn applies the In predicate on the "api" field.
func APIIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldIn(FieldAPI, vs...))
}

// APINotIn applies the NotIn predicate on the "api" field.
func APINotIn(vs ...string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldNotIn(FieldAPI, vs...))
}

// APIGT applies the GT predicate on the "api" field.
func APIGT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGT(FieldAPI, v))
}

// APIGTE applies the GTE predicate on the "api" field.
func APIGTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldGTE(FieldAPI, v))
}

// APILT applies the LT predicate on the "api" field.
func APILT(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLT(FieldAPI, v))
}

// APILTE applies the LTE predicate on the "api" field.
func APILTE(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldLTE(FieldAPI, v))
}

// APIContains applies the Contains predicate on the "api" field.
func APIContains(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContains(FieldAPI, v))
}

// APIHasPrefix applies the HasPrefix predicate on the "api" field.
func APIHasPrefix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasPrefix(FieldAPI, v))
}

// APIHasSuffix applies the HasSuffix predicate on the "api" field.
func APIHasSuffix(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldHasSuffix(FieldAPI, v))
}

// APIEqualFold applies the EqualFold predicate on the "api" field.
func APIEqualFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldEqualFold(FieldAPI, v))
}

// APIContainsFold applies the ContainsFold predicate on the "api" field.
func APIContainsFold(v string) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.FieldContainsFold(FieldAPI, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OtohaCatalogModel) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OtohaCatalogModel) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OtohaCatalogModel) predicate.OtohaCatalogModel {
	return predicate.OtohaCatalogModel(sql.NotPredicates(p))
}
